CREATE TABLE `match_substitutions` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `match_id` bigint(20) UNSIGNED NOT NULL,
  `team_side` enum('home','away') NOT NULL,
  `match_second` int(11) NOT NULL DEFAULT 0,
  `minute` int(11) NOT NULL,
  `minute_extra` int(11) DEFAULT NULL,
  `player_off_match_player_id` bigint(20) UNSIGNED NOT NULL,
  `player_on_match_player_id` bigint(20) UNSIGNED NOT NULL,
  `reason` enum('tactical','injury','fitness','disciplinary','unknown') NOT NULL DEFAULT 'unknown',
  `event_id` bigint(20) UNSIGNED DEFAULT NULL,
  `created_by` bigint(20) UNSIGNED NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_match_substitutions_match` (`match_id`),
  KEY `idx_match_substitutions_off` (`player_off_match_player_id`),
  KEY `idx_match_substitutions_on` (`player_on_match_player_id`),
  KEY `idx_match_substitutions_event` (`event_id`),
  KEY `idx_match_substitutions_created_by` (`created_by`),
  CONSTRAINT `fk_match_substitutions_match` FOREIGN KEY (`match_id`) REFERENCES `matches` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_match_substitutions_off` FOREIGN KEY (`player_off_match_player_id`) REFERENCES `match_players` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_match_substitutions_on` FOREIGN KEY (`player_on_match_player_id`) REFERENCES `match_players` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_match_substitutions_event` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_match_substitutions_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
