#!/bin/bash
echo "=== Match ID 19 Restoration Summary ==="
echo ""
echo "Matches: $(awk '/^-- matches/,/^-- events/ {print}' restore_match_19.sql | grep -c "^(19,")"
echo "Events: $(awk '/^-- events/,/^-- clips/ {print}' restore_match_19.sql | grep -c "^(.*19,")"
echo "Clips: $(awk '/^-- clips/,/^-- clip_jobs/ {print}' restore_match_19.sql | grep -c "^(.*19,")"
echo "Clip Jobs: $(awk '/^-- clip_jobs/,/^-- match_players/ {print}' restore_match_19.sql | grep -c "match_id.*19")"
echo "Match Players: $(awk '/^-- match_players/,/^-- match_formations/ {print}' restore_match_19.sql | grep -c "^(.*19,")"
echo "Match Formations: $(awk '/^-- match_formations/,/^-- match_periods/ {print}' restore_match_19.sql | grep -c "^(.*19,")"
echo "Match Periods: $(awk '/^-- match_periods/,/^-- match_videos/ {print}' restore_match_19.sql | grep -c "^(.*19,")"
echo "Match Videos: $(awk '/^-- match_videos/,/^-- derived_stats/ {print}' restore_match_19.sql | grep -c "^(.*19,")"
echo "Derived Stats: $(awk '/^-- derived_stats/,/^-- playlists/ {print}' restore_match_19.sql | grep -c "^(.*19,")"
echo "Playlists: $(awk '/^-- playlists/,/^-- match_locks/ {print}' restore_match_19.sql | grep -c "^(.*19,")"
echo "Match Locks: $(awk '/^-- match_locks/,/^SET FOREIGN_KEY_CHECKS/ {print}' restore_match_19.sql | grep -c "^(.*19,")"
